Repository redBorder/cookbook-rb-ale, pull requests merged in 2023-10, with the labels that each got.

#3 Modify name of service in consul
  .github/workflows/lint.yml
  Gemfile
  LICENSE
  packaging/rpm/cookbook-rb-ale.spec
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
Labels: kind/documentation, size/M

#4 Development
  resources/attributes/default.rb
  resources/providers/config.rb
Labels: kind/feature, size/S

#5 Adaptations to work on RHEL9
  README.md
  resources/providers/config.rb
Labels: size/S
